set(CONFIG_ARGS "--host=cray")
string(APPEND CFLAGS " -qopt-report -march=core-avx2")
string(APPEND FFLAGS " -qopt-report -march=core-avx2")
string(APPEND CFLAGS " -I$ENV{NCAR_INC_SUPERLU}")
string(APPEND LDFLAGS " -L$ENV{NCAR_LDFLAGS_SUPERLU} -lsuperlu")

if (COMP_NAME STREQUAL gptl)
  string(APPEND CPPDEFS " -DHAVE_SLASHPROC")
endif()
if (COMP_NAME STREQUAL mpi-serial)
  string(APPEND CFLAGS " -std=c89 ")
endif()
set(SCC icx)
set(SFC ifort)
